<?php

use Illuminate\Database\Seeder;

class BankTransactionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('bank_transactions')->delete();
        
        \DB::table('bank_transactions')->insert(array (
            0 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4360.672000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VIETTEL 400300 LIENNH 190701 1907 01064394155 400201 chuyen tien / FT19182736600464',
                'fund_in_account' => 'TCB-01',
                'id' => 1,
                'location' => '',
                'order_no' => '50000000001',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-01',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:11:55',
            ),
            1 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4360.672000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TKTT-DANG XUAN DUNG / FT19183669049776',
                'fund_in_account' => 'TCB-01',
                'id' => 2,
                'location' => '',
                'order_no' => '50000000002',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-02',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:11:47',
            ),
            2 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5310.672000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-HOANG HAI HA / FT19186730713127',
                'fund_in_account' => 'TCB-01',
                'id' => 3,
                'location' => '',
                'order_no' => '50000000003',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-05',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 18:22:46',
            ),
            3 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5510.672000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-PHAM TUAN / FT19187594543468',
                'fund_in_account' => 'TCB-01',
                'id' => 4,
                'location' => '',
                'order_no' => '50000000004',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-06',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 19:52:51',
            ),
            4 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5610.672000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-PHAM TUAN / FT19187339670077',
                'fund_in_account' => 'TCB-01',
                'id' => 5,
                'location' => '',
                'order_no' => '50000000005',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-06',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 18:10:23',
            ),
            5 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5609.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '200.000000',
                'currency' => 'VND',
                'debit' => '-1.100000',
                'deposit_id' => NULL,
                'description' => 'Thu phi Homebanking thang 7/2019 cua thue bao 0934440981 / HB 0934440981 20190708',
                'fund_in_account' => 'TCB-01',
                'id' => 6,
                'location' => '',
                'order_no' => '50000000006',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-08',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:12:16',
            ),
            6 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5598.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '-11.000000',
                'deposit_id' => NULL,
                'description' => 'Thu phi Homebanking thang 7/2019 cua thue bao 0934440981 / HB 0934440981 20190708',
                'fund_in_account' => 'TCB-01',
                'id' => 7,
                'location' => '',
                'order_no' => '50000000007',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-08',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 11:23:49',
            ),
            7 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '5498.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '-100.000000',
                'deposit_id' => NULL,
                'description' => 'T.Toan NAP TIEN - THUE BAO 0767554697 - K.HANG HOANG MINH TUYEN - 100000 VND - NGAY 08072019 / FT19189660067763',
                'fund_in_account' => 'TCB-01',
                'id' => 8,
                'location' => '',
                'order_no' => '50000000008',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-08',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 11:23:49',
            ),
            8 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '6498.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-VO YEN NHI / FT19189716195895',
                'fund_in_account' => 'TCB-01',
                'id' => 9,
                'location' => '',
                'order_no' => '50000000009',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-08',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:12:01',
            ),
            9 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '6598.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Ah / FT19190158070429',
                'fund_in_account' => 'TCB-01',
                'id' => 10,
                'location' => '',
                'order_no' => '50000000010',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 11:23:49',
            ),
            10 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '8598.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-VO THI TUYET HONG / FT19190796704209',
                'fund_in_account' => 'TCB-01',
                'id' => 11,
                'location' => '',
                'order_no' => '50000000011',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 16:30:57',
            ),
            11 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '3598.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '-5000.000000',
                'deposit_id' => NULL,
                'description' => 'DP TO BU TCB4012 5M / FT19190653228023',
                'fund_in_account' => 'TCB-01',
                'id' => 12,
                'location' => '',
                'order_no' => '50000000012',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 11:23:49',
            ),
            12 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4598.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'VND-TGTT-VO THI TUYET HONG / FT19190546000051',
                'fund_in_account' => 'TCB-01',
                'id' => 13,
                'location' => '',
                'order_no' => '50000000013',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 16:13:04',
            ),
            13 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '10000.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 14,
                'location' => '',
                'order_no' => '50000000014',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 17:31:55',
            ),
            14 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 15,
                'location' => '',
                'order_no' => '50000000015',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:12:47',
            ),
            15 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 16,
                'location' => '',
                'order_no' => '50000000016',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:12:43',
            ),
            16 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 17,
                'location' => '',
                'order_no' => '50000000017',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            17 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 18,
                'location' => '',
                'order_no' => '50000000018',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            18 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 19,
                'location' => '',
                'order_no' => '50000000019',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 18:38:19',
            ),
            19 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 20,
                'location' => '',
                'order_no' => '50000000020',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            20 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 21,
                'location' => '',
                'order_no' => '50000000021',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            21 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 22,
                'location' => '',
                'order_no' => '50000000022',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 19:57:35',
            ),
            22 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '197.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 23,
                'location' => '',
                'order_no' => '50000000023',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 19:55:37',
            ),
            23 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 24,
                'location' => '',
                'order_no' => '50000000024',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            24 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 25,
                'location' => '',
                'order_no' => '50000000025',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-23 12:37:13',
            ),
            25 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 26,
                'location' => '',
                'order_no' => '50000000026',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-23 12:35:50',
            ),
            26 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 27,
                'location' => '',
                'order_no' => '50000000027',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            27 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 28,
                'location' => '',
                'order_no' => '50000000028',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:11:57',
            ),
            28 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 29,
                'location' => '',
                'order_no' => '50000000029',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 20:48:08',
            ),
            29 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 30,
                'location' => '',
                'order_no' => '50000000030',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 20:43:28',
            ),
            30 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 31,
                'location' => '',
                'order_no' => '50000000031',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 19:12:29',
            ),
            31 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 32,
                'location' => '',
                'order_no' => '50000000032',
                'remark' => '',
                'status' => 1,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-21 13:58:42',
            ),
            32 => 
            array (
                'account_no' => '',
                'admin_name' => 'left',
                'balance' => '4798.572000',
                'bank_code' => 'TCB',
                'bank_reference' => '',
                'channel' => '',
                'created_at' => '2019-08-21 11:23:49',
                'credit' => '100.000000',
                'currency' => 'VND',
                'debit' => '0.000000',
                'deposit_id' => NULL,
                'description' => 'Truong van tung ck / FT19190052602290',
                'fund_in_account' => 'TCB-01',
                'id' => 33,
                'location' => '',
                'order_no' => '50000000033',
                'remark' => '',
                'status' => 2,
                'transaction_at' => NULL,
                'transaction_date' => '2019-07-09',
                'transaction_id' => '',
                'transfer_details' => '',
                'updated_at' => '2019-08-22 13:04:43',
            ),
        ));
        
        
    }
}