<?php

use Illuminate\Database\Seeder;
use App\Models\Currency;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        Currency::query()->truncate();

        $now = now();

        if (app()->isLocal()) {
            $currencies = [
                [
                    'id'                               => 1,
                    'name'                             => 'CNY',
                    'code'                             => 'CNY',
                    'preset_language'                  => 'zh-CN',
                    'country'                          => 'China',
                    'country_code'                     => '+86',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 1000,
                ],
                [
                    'id'                               => 2,
                    'name'                             => 'USD',
                    'code'                             => 'USD',
                    'preset_language'                  => 'en-US',
                    'country'                          => 'United Kiongdom',
                    'country_code'                     => '+44',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 500,
                ],
                [
                    'id'                               => 3,
                    'name'                             => 'VND',
                    'code'                             => 'VND',
                    'preset_language'                  => 'vi-VN',
                    'country'                          => 'Vietnam',
                    'country_code'                     => '+84',
                    'is_remove_three_zeros'            => true,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 2000000,
                ],
                [
                    'id'                               => 4,
                    'name'                             => 'THB',
                    'code'                             => 'THB',
                    'preset_language'                  => 'th',
                    'country'                          => 'Thailand',
                    'country_code'                     => '+66',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 2500,
                ],
            ];
        } else {
            $currencies = [
                [
                    'id'                               => 1,
                    'name'                             => 'CNY',
                    'code'                             => 'CNY',
                    'preset_language'                  => 'zh-CN',
                    'country'                          => 'China',
                    'country_code'                     => '+86',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 1000,
                ],
                [
                    'id'                               => 2,
                    'name'                             => 'USD',
                    'code'                             => 'USD',
                    'preset_language'                  => 'en-US',
                    'country'                          => 'United Kiongdom',
                    'country_code'                     => '+44',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 500,
                ],
                [
                    'id'                               => 3,
                    'name'                             => 'VND',
                    'code'                             => 'VND',
                    'preset_language'                  => 'vi-VN',
                    'country'                          => 'Vietnam',
                    'country_code'                     => '+84',
                    'is_remove_three_zeros'            => true,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 2000000,
                ],
                [
                    'id'                               => 4,
                    'name'                             => 'THB',
                    'code'                             => 'THB',
                    'preset_language'                  => 'th',
                    'country'                          => 'Thailand',
                    'country_code'                     => '+66',
                    'is_remove_three_zeros'            => false,
                    'max_deposit'                      => 45000,
                    'min_deposit'                      => 100,
                    'max_withdrawal'                   => 5000,
                    'min_withdrawal'                   => 300,
                    'max_daily_withdrawal'             => 45000,
                    'min_transfer'                     => 1,
                    'max_transfer'                     => 1000000,
                    'status'                           => true,
                    'sort'                             => 0,
                    'created_at'                       => $now,
                    'updated_at'                       => $now,
                    'deposit_second_approve_amount'    => 10000,
                    'withdrawal_second_approve_amount' => 7000,
                    'bank_account_verify_amount'       => 300,
                    'info_verify_prize_amount'         => 50,
                    'commission'                       => 10,
                    'payout_comm_mini_limit'           => 2500,
                ],
            ];
        }

        Currency::query()->insert($currencies);
    }
}
