<?php

use Illuminate\Database\Seeder;

class PromotionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('promotions')->delete();

        \DB::table('promotions')->insert(array(
            0  =>
                array(
                    'id'                      => 3,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "15% SLOTS WEEKLY CASHBACK", "content": "<h2><br></h2><h2><strong style=\\"color: rgb(253, 181, 20);\\">﻿</strong><strong style=\\"color: rgb(253, 181, 20);\\" class=\\"ql-size-large\\">Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(26, 26, 26);\\">01/09/2019 00:00:00 (GMT +8)</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">until </span><strong style=\\"color: rgb(26, 26, 26);\\">30/09/2019 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(102, 102, 102);\\">, applies for members registered with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Members need to bet in Playtech Slot and claim 15% weekly slots bonus from total loss within a week.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout THB 200 and maximum payout THB 1500.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Each member can claim ONCE a week during promotion period.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Member need to click Claim Button to avail this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets and some game are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount will be credited into members wallet every Tuesday.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount need to meet 5 times rollover at Playtech slot before any withdrawal can be made.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions.</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">EG General Terms &amp; Conditions</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">Apply.</span></li></ol>", "currency": "VND", "description": "Members need to bet in Microgaming Slot and claim 15% weekly slots bonus from total loss within a week."}]',
                    'promotion_type_code'     => 'slot',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-15% Slots Weekly Cashback',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567736342_ooXpzVZaIm.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567736351_PhWIDfVz1u.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567736362_6uOgD84kuy.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567736370_ywp0cUHO8e.jpg',
                    'status'                  => 1,
                    'sort'                    => 8,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-02 16:08:49',
                    'updated_at'              => '2019-09-06 15:33:25',
                ),
            1  =>
                array(
                    'id'                      => 4,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "0.5% DAILY REBATE GAMES", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Promotion Offer</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion applies for member registered member with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(24, 24, 24);\\">01/09/2019 00:00:00 (GMT+8)</strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion will base on total eligible stake amount at EG Slots.</span></li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Condition</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Rebate amount will be based on total eligible stake amount from </span><strong style=\\"color: rgb(102, 102, 102);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> until </span><strong style=\\"color: rgb(102, 102, 102);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> daily.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout is 10 THB and no limit maximum payout.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">There is no rollover requirement and credited daily.</span><sup style=\\"color: rgb(24, 24, 24);\\"><strong><em>Note: Rebate amount cannot combine within different provider of Games</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All eligible stakes settled 48 hours prior will be include in the rebate calculation</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Welcome promotion, daily reload promotion in Empiregem page will not applicable once members claimed this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions</span></li><li><strong style=\\"color: rgb(102, 102, 102);\\">EG General Terms &amp; Conditions</strong><span style=\\"color: rgb(102, 102, 102);\\"> Apply</span></li></ol>", "currency": "VND", "description": "Get a good offer in our room: EG Games."}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-0.5% Daily Rebate Games',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567743030_QCQVVCRYSq.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567743044_ASFQEYLZpw.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567743451_wO4xJjVUDj.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567743458_erjV8MrWeT.jpg',
                    'status'                  => 1,
                    'sort'                    => 6,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-05 17:26:50',
                    'updated_at'              => '2019-09-06 15:31:35',
                ),
            2  =>
                array(
                    'id'                      => 5,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "โปรสุดป๊อบ! เกมส์สล็อตรับเงินคืนทุกสัปดาห์!โปรสุดป๊อบ! เกมส์สล็อตรับเงินคืนทุกสัปดาห์!", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข</strong><span class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">1</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">00:00:00 (GMT +8)</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ถึงวันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">30</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">23:59:59 (GMT+8)</strong><strong style=\\"color: rgb(102, 102, 102);\\">, </strong><span style=\\"color: rgb(102, 102, 102);\\">สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท </span><strong style=\\"color: rgb(26, 26, 26);\\">(THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกจะต้องเดิมพันกับ Microgaming Slot จึงจะสามารถรับรับเงินคืน 15% ทุกสัปดาห์ จากยอดเสียทั้งหมดภายในสัปดาห์นั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ยอดการจ่ายขั้นต่ำ 200 บาท และสูงสุด 1,500 บาท</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกแต่ละท่านสามารถรับโปรโมชั่นได้เพียงหนึ่งครั้งในช่วงระยะเวลาตามที่กำหนด</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกต้องคลิกปุ่มรับสิทธิ์ เพื่อใช้สิทธิ์จากโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, และเกมส์อื่น ๆ จะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ยอดโบนัสจะเข้าสู่บัญชีเครดิตของสมาชิกทุกวันอังคาร</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสที่ได้รับจะต้องมียอดเดิมพันหมุนเวียน 5 เท่า ในผลิตภัณฑ์ Microgaming ก่อน จึงจะสามารถทำการถอนได้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">﻿</span><strong style=\\"color: rgb(26, 26, 26);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "สำหรับสมาชิกที่เดิมพันกับ Microgaming รับเลย 15% ทุกสัปดาห์"}]',
                    'promotion_type_code'     => 'slot',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-15% Slots Weekly Cashback',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567747974_83FbATLQVK.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567747979_1fTPJGboXI.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567747982_3399Yu5Vet.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567747986_LFH82gVJQI.jpg',
                    'status'                  => 1,
                    'sort'                    => 8,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 10:40:33',
                    'updated_at'              => '2019-09-06 15:33:18',
                ),
            3  =>
                array(
                    'id'                      => 6,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "NEW SEASON NEW WINNING", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from</span><span style=\\"color: rgb(26, 26, 26);\\"> </span><strong style=\\"color: rgb(26, 26, 26);\\">01/09/2019 00:00:00 (GMT +8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> until </span><strong style=\\"color: rgb(26, 26, 26);\\">30/09/2019 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(102, 102, 102);\\">, applies for members registered with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">The promotion only applies for first 100 qualified members.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Members need to have total deposit amount is THB 300 or above during promotion period.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Members need to bet English Premier League of Sphere Sports as following:</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Each member can claim ONCE during promotion period.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount will be credited into members wallet after 24 hours when promotion ends.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount need to meet 6 times rollover at Sphere Sports before any withdrawal can be made.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, bets under odd HK 0.5 (equal to under Malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions.</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">EG General Terms &amp; Conditions</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">Apply.</span></li></ol>", "currency": "VND", "description": "Play in English Premier League market and get now THB 1,000!"}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-New Season New Winning',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567740099_jbhrpzYGY3.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567740103_EaTaVX0jDs.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567740111_KW9vtn9Lxr.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567740118_qJ35NQtYEw.jpg',
                    'status'                  => 1,
                    'sort'                    => 7,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 11:34:46',
                    'updated_at'              => '2019-09-06 15:31:57',
                ),
            4  =>
                array(
                    'id'                      => 7,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "แมตช์นี้ต้องมีเฮ!", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข</strong><span class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">1</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(26, 26, 26);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">00:00:00 (GMT +8)</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ถึงวันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">30</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">23:59:59 (GMT+8)</strong><strong style=\\"color: rgb(102, 102, 102);\\">, </strong><span style=\\"color: rgb(102, 102, 102);\\">สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท </span><span style=\\"color: rgb(26, 26, 26);\\">(</span><strong style=\\"color: rgb(26, 26, 26);\\">THB)</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้สำหรับลูกค้า 100 ท่านแรกเท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกจะต้องมียอดเงินฝากรวม 300 บาทขึ้นไป ในช่วงระยะเวลาโปรโมชั่นดังกล่าว</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกจะต้องเดิมพันในพรีเมียร์ลีกอังกฤษของ Sphere Sports ดังนี้:</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">&nbsp;&nbsp;สมาชิกแต่ละท่านสามารถรับโปรโมชั่นได้เพียงหนึ่งครั้งในช่วงระยะเวลาตามที่กำหนด</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">&nbsp;สมาชิกจะได้รับโบนัสเข้าบัญชี (wallet) หลังจากที่โปรโมชั่นสิ้นสุดแล้ว 24 ชั่วโมง (เวลาทำการปกติ)</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสที่ได้รับจะต้องมียอดเดิมพันหมุนเวียน 6 ครั้งกับ&nbsp;</span><u style=\\"color: rgb(102, 102, 102);\\">EG Sports</u><span style=\\"color: rgb(102, 102, 102);\\"> ก่อน จึงจะสามารถถอนเงินออกจากบัญชีได้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">&nbsp;การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, การเดิมพันฝั่งตรงข้าม, การเดิมพันต่ำกว่าราคาค่าน้ำ ฮ่องกง 0.5,&nbsp;(หรือเท่ากับ/ต่ำกว่าราคาค่าน้ำมาเลย์ 0.5, ต่ำกว่าราคาค่าน้ำอินโด -2.00, ต่ำกว่าราคาค่าน้ำ US-200 และต่ำกว่าราคาค่าน้ำเดซิมอล 1.5) เสียครึ่ง, ได้ครึ่ง และไม่รวมรายการม้าแข่ง ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">&nbsp;Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "ลุ้นพรีเมียร์ ลีค กับ Empiregem รับเลย 1,000 บาท"}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-New season new winning',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567747894_R8jezL1BaX.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567747898_bKFjCXAFHQ.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567747901_ZDongTHbGE.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567747905_eWfGHI8cNU.jpg',
                    'status'                  => 0,
                    'sort'                    => 7,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 11:53:48',
                    'updated_at'              => '2019-09-06 15:32:03',
                ),
            5  =>
                array(
                    'id'                      => 8,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "10% SPORTS WEEKLY CASHBACK", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts </span><strong style=\\"color: rgb(26, 26, 26);\\">01/09/2019 00:00:00 (GMT +8)</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">until </span><span style=\\"color: rgb(26, 26, 26);\\">3</span><strong style=\\"color: rgb(26, 26, 26);\\">0/09/2019 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(26, 26, 26);\\">,</span><span style=\\"color: rgb(102, 102, 102);\\"> applies for members registered with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Member need to play in EG Sports and claim 20% weekly bonus from total loss within a week.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout THB 300 and maximum payout THB 2000.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Member only can claim ONCE a week during promotion period.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Member need to click Claim Button to avail this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, bets under odd HK 0.5 (equal to under Malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount will be credited into members wallet every Tuesday.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Bonus amount need to meet 8 times rollover at EG Sports before any withdrawal can be made.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions.</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">EG General Terms &amp; Conditions</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">Apply.</span></li></ol>", "currency": "VND", "description": "Member need to play in EG Sports and claim 10% weekly bonus from total loss within a week."}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-10% Sports Weekly Cashback',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567747760_0tXRYqfwyZ.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567747772_2piD3y0RiL.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567747776_17wLX4ngyc.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567747780_NxUJqf3nKG.jpg',
                    'status'                  => 1,
                    'sort'                    => 10,
                    'admin_name'              => 'erin',
                    'created_at'              => '2019-09-06 12:08:39',
                    'updated_at'              => '2019-09-06 15:50:57',
                ),
            6  =>
                array(
                    'id'                      => 9,
                    'currencies'              => '["USD"]',
                    'languages'               => '[{"title": "1234", "content": "1<u>23412341<em>23412341</em></u>234<span style=\\"background-color:#E56600;\\">1234123412341234<strong>123412341234214</strong><strong></strong><strong></strong></span>", "currency": "USD", "description": "1234"}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-10% Sports Weekly Cashback',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567743717_NbuE1U2tIK.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567743725_ltEnXKC7Tc.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567743729_UhSDPmQjyp.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567743733_9zBrKw6ENE.jpg',
                    'status'                  => 1,
                    'sort'                    => 10,
                    'admin_name'              => 'left',
                    'created_at'              => '2019-09-06 12:23:45',
                    'updated_at'              => '2019-09-09 15:48:13',
                ),
            7  =>
                array(
                    'id'                      => 10,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "รับเลย! ไม่ต้องเทิร์นโอเวอร์", "content": "<p><br></p><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">สุดพิเศษสำหรับสมาชิก:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(24, 24, 24);\\">1 ก.ย. 62 เวลา 00:00:00 (GMT +8) </strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสคืนเงินจะถูกจ่ายออกหลังจากยอดเดิมพันหมุนเวียนทั้งหมดในหน้า EG Games.</span></li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินคืนจะขึ้นอยู่กับจำนวนเงินเดิมพันที่มีสิทธิ์ทั้งหมด ตั้งแต่เวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> ถึงเวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ของทุกวัน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินที่จ่ายออกเริ่มต้นที่ 10 บาทขึ้นไป และไม้จำกัดในการจ่ายออก</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ไม่ต้องทำเทิร์นโอเวอร์และปรับเครดิตให้ทุกวัน </span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>หมายเหตุ: จำนวนเงินคืนที่ได้รับ ไม่สามารถนำมารวมกันกับ Games แบรนด์อื่นๆ ได้</em></strong></sup><strong style=\\"color: rgb(102, 102, 102);\\"><em> </em></strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ และการเดิมพันฝั่งตรงข้าม ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">รายการเดิมพันที่มีการปรับผลภายใน 48 ชั่วโมง จะถูกนับรวมในการคำนวณยอดสำหรับโบนัสเงินคืนด้วย</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นต้อนรับ, โปรโมชั่นรายวัน จาก Empiregem จะไม่สามารถใช้ได้ หากสมาชิกทำการรับโปรโมชั่นนี้แล้ว</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "เงินคืน 0.5% ในหน้า EG Slots ได้ทุกวัน!"}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-0.5% Daily Rebate Games',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/16/9_1568600702_XqXHBrbPeB.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/16/9_1568600709_ApblW0w0ob.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/16/9_1568600719_4Gv3NXokWD.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/16/9_1568600727_LOmaTkA1I7.jpg',
                    'status'                  => 1,
                    'sort'                    => 6,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 12:29:45',
                    'updated_at'              => '2019-09-16 10:25:31',
                ),
            8  =>
                array(
                    'id'                      => 11,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "0.3% DAILY REBATE SPORTSBOOK", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Promotion Offer:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion applies for member registered member with currency THB. </span></li><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(24, 24, 24);\\">01/09/2019 00:00:00 (GMT+8)</strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion will base on total eligible stake amount at EG Sports, Sphere Sports and Realm Sports</span>.</li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Condition</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Rebate amount will be based on total eligible stake amount from </span><strong style=\\"color: rgb(24, 24, 24);\\">00:00:01 (GMT +8) </strong><span style=\\"color: rgb(102, 102, 102);\\">until </span><strong style=\\"color: rgb(24, 24, 24);\\">23:59:59 (GMT+8) </strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">daily.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout is THB 10 and no limit maximum payout.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">There is no rollover requirement and credited daily.</span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>Note: Rebate amount cannot combine within 3 sports</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, under odds HK 0.5 (equal to under malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All eligible stakes settled 48 hours prior will be include in the rebate calculation</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Welcome promotion, daily reload promotion in Empiregem page will not applicable once members claimed this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">EG General Terms &amp; Conditions Apply</strong></li></ol>", "currency": "VND", "description": "Get a good offer in our room: EG, Sphere and Realm."}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-0.3% Daily Rebate Sportsbook',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567744682_HuCKtcmpex.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567744687_SE8HiOM6Cg.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567744693_o1zfrPYrqN.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567744699_idsnbSpMFk.jpg',
                    'status'                  => 1,
                    'sort'                    => 3,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 12:51:56',
                    'updated_at'              => '2019-09-06 15:30:24',
                ),
            9  =>
                array(
                    'id'                      => 12,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "0.5% DAILY REBATE SLOTS", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Promotion Offer:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion applies for member registered member with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts </span><span style=\\"color: rgb(26, 26, 26);\\">from </span><strong style=\\"color: rgb(26, 26, 26);\\">01/09/2019 00:00:00 (GMT+8)</strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion will base on total eligible stake amount at EG Slots.</span></li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Condition</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Rebate amount will be based on total eligible stake amount from </span><span style=\\"color: rgb(26, 26, 26);\\">00:00:01 (GMT +8)</span><span style=\\"color: rgb(102, 102, 102);\\"> until </span><span style=\\"color: rgb(26, 26, 26);\\">23:59:59 (GMT+8)</span><span style=\\"color: rgb(102, 102, 102);\\"> daily.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout is 10 THB and no limit maximum payout.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">There is no rollover requirement and credited daily. </span><sup style=\\"color: rgb(26, 26, 26);\\">Note: Rebate amount cannot combine within different provider of slots</sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All eligible stakes settled 48 hours prior will be include in the rebate calculation</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Welcome promotion, daily reload promotion in Empiregem page will not applicable once members claimed this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">EG General Terms &amp; Conditions</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">Apply.</span></li></ol>", "currency": "VND", "description": "Get a good offer in our room: EG Slots."}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-0.5% DAILY REBATE SLOTS',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567748103_9OkLhBsU9i.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567748106_diZJX2pPtN.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567748111_N16o8jWiGC.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567748118_jG8HhcTyOs.jpg',
                    'status'                  => 1,
                    'sort'                    => 5,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 12:53:17',
                    'updated_at'              => '2019-09-06 15:31:02',
                ),
            10 =>
                array(
                    'id'                      => 13,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "รับเลย! ไม่ต้องเทิร์นโอเวอร์", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">﻿สุดพิเศษสำหรับสมาชิก</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(24, 24, 24);\\">1 ก.ย. 62 เวลา 00:00:00 (GMT +8) </strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสคืนเงินจะถูกจ่ายออกหลังจากยอดเดิมพันหมุนเวียนทั้งหมดในหน้า EG Sports, Sphere Sports และ Realm Sports.</span></li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินคืนจะขึ้นอยู่กับจำนวนเงินเดิมพันที่มีสิทธิ์ทั้งหมด ตั้งแต่เวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ถึงเวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ของทุกวัน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินที่จ่ายออกเริ่มต้นที่ </span><strong style=\\"color: rgb(102, 102, 102);\\">10</strong><span style=\\"color: rgb(102, 102, 102);\\"> บาทขึ้นไป และไม่จำกัดในการจ่ายออก</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ไม่ต้องทำเทิร์นโอเวอร์และปรับเครดิตให้ทุกวัน</span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>หมายเหตุ: จำนวนเงินคืนที่ได้รับ ไม่สามารถนำมารวมกันใน Sports ทั้ง 3 แบบได้ </em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, การเดิมพันฝั่งตรงข้าม, การเดิมพันต่ำกว่าราคาค่าน้ำ ฮ่องกง 0.5, (หรือเท่ากับ/ต่ำกว่าราคาค่าน้ำมาเลย์ 0.5, ต่ำกว่าราคาค่าน้ำอินโด -2.00, ต่ำกว่าราคาค่าน้ำ US-200 และต่ำกว่าราคาค่าน้ำเดซิมอล 1.5) เสียครึ่ง, ได้ครึ่ง และไม่รวมรายการม้าแข่ง ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">รายการเดิมพันที่มีการปรับผลภายใน 48 ชั่วโมง จะถูกนับรวมในการคำนวณยอดสำหรับโบนัสเงินคืนด้วย</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นต้อนรับ, โปรโมชั่นรายวัน จาก Empiregem จะไม่สามารถใช้ได้ หากสมาชิกทำการรับโปรโมชั่นนี้แล้ว</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "เงินคืน 0.3% ในหน้า Sportbook, EG, Sphere และ Realm ได้ทุกวัน!"}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-0.3% Daily Rebate Sportsbook',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567745997_v4XwSZUh9z.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567746005_qb19QpdQAz.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567746012_5ZIkuYL3Q2.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567746018_riZ3YRpevY.jpg',
                    'status'                  => 1,
                    'sort'                    => 3,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 13:03:54',
                    'updated_at'              => '2019-09-06 15:29:58',
                ),
            11 =>
                array(
                    'id'                      => 14,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "รับเลย! ไม่ต้องเทิร์นโอเวอร์", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">สุดพิเศษสำหรับสมาชิก:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: black;\\">1</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: black;\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา</span><span style=\\"color: black;\\"> </span><strong style=\\"color: black;\\">00:00:00 (GMT +8) </strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสคืนเงินจะถูกจ่ายออกหลังจากยอดเดิมพันหมุนเวียนทั้งหมดในหน้า EG Slots</span></li></ol><h2><span class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินคืนจะขึ้นอยู่กับจำนวนเงินเดิมพันที่มีสิทธิ์ทั้งหมด ตั้งแต่เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ถึงเวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ของทุกวัน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินที่จ่ายออกเริ่มต้นที่</span><strong style=\\"color: rgb(102, 102, 102);\\"> 10 </strong><span style=\\"color: rgb(102, 102, 102);\\">บาทขึ้นไป และไม้จำกัดในการจ่ายออก</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ไม่ต้องทำเทิร์นโอเวอร์และปรับเครดิตให้ทุกวัน </span><sup style=\\"color: black;\\">หมายเหตุ: จำนวนเงินคืนที่ได้รับ ไม่สามารถนำมารวมกันกับ Slot Games แบรนด์อื่นๆ ได้ </sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ และการเดิมพันฝั่งตรงข้าม ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">รายการเดิมพันที่มีการปรับผลภายใน 48 ชั่วโมง จะถูกนับรวมในการคำนวณยอดสำหรับโบนัสเงินคืนด้วย</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นต้อนรับ, โปรโมชั่นรายวัน จาก Empiregem จะไม่สามารถใช้ได้ หากสมาชิกทำการรับโปรโมชั่นนี้แล้ว</span><strong style=\\"color: rgb(102, 102, 102);\\">&nbsp;&nbsp;</strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: black;\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "เงินคืน 0.5% ในหน้า EG Slots ได้ทุกวัน!"}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-0.5% DAILY REBATE SLOTS',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567746016_gTu9hyfQme.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567746020_MxJPZXXA7m.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567746023_wxKJEVf5wm.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567746027_n0krEJWoIf.jpg',
                    'status'                  => 1,
                    'sort'                    => 5,
                    'admin_name'              => 'erin',
                    'created_at'              => '2019-09-06 13:04:53',
                    'updated_at'              => '2019-09-07 09:10:45',
                ),
            12 =>
                array(
                    'id'                      => 15,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "0.6% DAILY REBATE LIVE CASINO", "content": "<p><br></p><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Promotion Offer:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion applies for member registered member with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(24, 24, 24);\\">01/09/2019 00:00:00 (GMT+8)</strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">Promotion will base on total eligible stake amount at The Royal Palace, Grand Palace, Luxury Palace and Majesty Palace.</span></li></ol><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">Terms &amp; Condition</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">Rebate amount will be based on total eligible stake amount from </span><strong style=\\"color: rgb(24, 24, 24);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> until </span><strong style=\\"color: rgb(24, 24, 24);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">daily.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Minimum payout is 10 THB and no limit maximum payout.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">There is no rollover requirement and credited daily.</span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>Note: Rebate amount cannot combine within 4 Live Casino</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All eligible stakes settled 48 hours prior will be include in the rebate calculation</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Welcome promotion, daily reload promotion in Empiregem page will not applicable once members claimed this promotion.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions</span></li><li><strong style=\\"color: rgb(102, 102, 102);\\">EG General Terms &amp; Conditions Apply</strong></li></ol>", "currency": "VND", "description": "Get a good offer in our room: Royal, Grand, Luxury and Majesty."}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-0.6% Daily Rebate Live Casino',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567746715_GXHm7dVfPx.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567746720_DYWtnMq8Cz.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567746726_vEIBA1bEf5.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567746731_aQINdJOJjm.jpg',
                    'status'                  => 1,
                    'sort'                    => 4,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 13:12:55',
                    'updated_at'              => '2019-09-06 15:30:39',
                ),
            13 =>
                array(
                    'id'                      => 16,
                    'currencies'              => '["VND"]',
                    'languages'               => '[{"title": "WIN PTT THAILAND GRAND PRIX TICKETS", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">﻿Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(26, 26, 26);\\">01/09/2019 00:00:00 (GMT +8)</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">until </span><span style=\\"color: rgb(26, 26, 26);\\">3</span><strong style=\\"color: rgb(26, 26, 26);\\">0/09/2019 23:59:59 (GMT+8</strong><span style=\\"color: rgb(26, 26, 26);\\">)</span><span style=\\"color: rgb(102, 102, 102);\\">, applies for members registered with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Members need to bet at EG Sports as following requirement”</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Each member can claim ONCE during promotion period.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, bets under odd HK 0.5 (equal to under Malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Winner list will be announced after 48 working hours when promotion ends.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Prize cannot be exchange with cash, freebet or any prize.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Members need to provided exactly delivery information as: Full name, Contact Number and address before 30/09/2019) or will be forfeited the winning.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time and forfeited the bonus if it detects members who are string bets, group bets, linked other accounts and abuse of the promotions.</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">EG General Terms &amp; Conditions</strong><span style=\\"color: rgb(26, 26, 26);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">Apply.</span></li></ol>", "currency": "VND", "description": "Get a chance to win tickets in the biggest event of the year!"}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-WIN PTT THAILAND GRAND PRIX TICKETS',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567747081_6huoznHS16.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567747085_Hla0OGfpBZ.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567747089_DbBPJ6Sd5H.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567747093_ybwVaWlkrI.jpg',
                    'status'                  => 1,
                    'sort'                    => 9,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 13:20:02',
                    'updated_at'              => '2019-09-06 15:33:35',
                ),
            14 =>
                array(
                    'id'                      => 17,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "รับเลย! ไม่ต้องเทิร์นโอเวอร์", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">﻿สุดพิเศษสำหรับสมาชิก:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(24, 24, 24);\\">1 ก.ย. 62 เวลา 00:00:00 (GMT +8) </strong></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสคืนเงินจะถูกจ่ายออกหลังจากยอดเดิมพันหมุนเวียนทั้งหมดในหน้า The Royal Palace, Grand Palace, Luxury Palace และ Majesty Palace.</span></li></ol><h2><span class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินคืนจะขึ้นอยู่กับจำนวนเงินเดิมพันที่มีสิทธิ์ทั้งหมด ตั้งแต่เวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">00:00:01 (GMT +8)</strong><span style=\\"color: rgb(102, 102, 102);\\"> ถึงเวลา </span><strong style=\\"color: rgb(24, 24, 24);\\">23:59:59 (GMT+8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">ของทุกวัน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">จำนวนเงินที่จ่ายออกเริ่มต้นที่ </span><strong style=\\"color: rgb(102, 102, 102);\\">10</strong><span style=\\"color: rgb(102, 102, 102);\\"> บาทขึ้นไป และไม้จำกัดในการจ่ายออก</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">ไม่ต้องทำเทิร์นโอเวอร์และปรับเครดิตให้ทุกวัน</span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>หมายเหตุ: จำนวนเงินคืนที่ได้รับ ไม่สามารถนำมารวมกันใน Live casino ทั้ง 4 แบบได้ </em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ และการเดิมพันฝั่งตรงข้าม ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">รายการเดิมพันที่มีการปรับผลภายใน 48 ชั่วโมง จะถูกนับรวมในการคำนวณยอดสำหรับโบนัสเงินคืนด้วย</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นต้อนรับ, โปรโมชั่นรายวัน จาก Empiregem จะไม่สามารถใช้ได้ หากสมาชิกทำการรับโปรโมชั่นนี้แล้ว</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "เงินคืน 0.6% ในหน้า Royal, Grand, Luxury และ Majesty ได้ทุกวัน!"}]',
                    'promotion_type_code'     => 'rebate',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-0.6% Daily Rebate Live Casino',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567746933_WH9vaxTqyR.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567746937_DwQlZJOexH.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567746943_Zw3ziCbo6D.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567746948_4xItAXoxSM.jpg',
                    'status'                  => 1,
                    'sort'                    => 4,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 13:20:40',
                    'updated_at'              => '2019-09-06 15:30:45',
                ),
            15 =>
                array(
                    'id'                      => 18,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "ลุ้นรับบัตร PTT Thailand Grand Prix", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">ข้อตกลงและเงื่อนไข</strong><span class=\\"ql-size-large\\" style=\\"color: rgb(253, 181, 20);\\">:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">1</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">00:00:00 (GMT +8) </strong><span style=\\"color: rgb(102, 102, 102);\\">ถึงวันที่ </span><strong style=\\"color: rgb(26, 26, 26);\\">30</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">ก.ย. </span><strong style=\\"color: rgb(26, 26, 26);\\">62</strong><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">เวลา </span><strong style=\\"color: rgb(26, 26, 26);\\">23:59:59 (GMT+8)</strong><strong style=\\"color: rgb(102, 102, 102);\\">, </strong><span style=\\"color: rgb(102, 102, 102);\\">สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกจะต้องเดิมพันกับ EG Sports ตามข้อกำหนด ดังนี้:</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกแต่ละท่านสามารถรับโปรโมชั่นได้เพียงหนึ่งครั้งในช่วงระยะเวลาตามที่กำหนด</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">&nbsp;การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, การเดิมพันฝั่งตรงข้าม, การเดิมพันต่ำกว่าราคาค่าน้ำ ฮ่องกง 0.5,&nbsp;(หรือเท่ากับ/ต่ำกว่าราคาค่าน้ำมาเลย์ 0.5, ต่ำกว่าราคาค่าน้ำอินโด -2.00, ต่ำกว่าราคาค่าน้ำ US-200 และต่ำกว่าราคาค่าน้ำเดซิมอล 1.5) เสียครึ่ง, ได้ครึ่ง และไม่รวมรายการม้าแข่ง ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สำหรับรายชื่อผู้ชนะจะประกาศหลังจากโปรโมชั่นสิ้นสุดแล้ว 48 ชั่วโมง (เวลาทำการปกติ)</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">รางวัลไม่สามารถเปลี่ยนแปลงเป็นเงินสด เครดิตฟรี หรือทดแทนเป็นอย่างอื่นได้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">สมาชิกจะต้องแจ้งข้อมูลในการจัดส่งที่ถูกต้อง เช่น ชื่อ-นามสกุล, ที่อยู่, หมายเลขโทรศัพท์สำหรับการติดต่อ ก่อนวันที่ 30 ก.ย. 62 หากไม่แจ้งข้อมูลภายในระยะเวลาดังกล่าวจะถือว่าสละสิทธิ์ในการรับของรางวัล</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการเปลี่ยนแปลง แก้ไขและยกเลิกโปรโมชั่นนี้ โดยไม่ต้องแจ้งให้ทราบล่วงหน้า และริบโบนัส หากตรวจพบสมาชิกที่เดิมพันแบบสตริง การเดิมพันกลุ่มการเชื่อมโยงบัญชีอื่น ๆ และการใช้โปรโมชั่นในทางที่ผิด</span></li><li><strong style=\\"color: rgb(26, 26, 26);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "เป็นเจ้าของบัตรที่นั่ง PTT Thailand Grand Prix  รอบชิงชนะเลิศ กับ Empiregem วันนี้"}]',
                    'promotion_type_code'     => 'sport',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-WIN PTT THAILAND GRAND PRIX TICKETS',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/8_1567747244_jGaIVBv1YP.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/8_1567747248_QVT3Pa9ks4.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/8_1567747253_SjctyfhPML.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/8_1567747256_Zm5LfZyEqj.jpg',
                    'status'                  => 0,
                    'sort'                    => 9,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 13:22:51',
                    'updated_at'              => '2019-09-06 15:33:41',
                ),
            16 =>
                array(
                    'id'                      => 19,
                    'currencies'              => '["USD"]',
                    'languages'               => '[{"title": "100% SIGN UP BONUS", "content": "<h2><br></h2><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(251, 213, 20);\\">Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(24, 24, 24);\\">01/09/2019 00:00:00 (GMT +8)</strong><span style=\\"color: rgb(24, 24, 24);\\"> </span><span style=\\"color: rgb(102, 102, 102);\\">until </span><strong style=\\"color: rgb(24, 24, 24);\\">30/09/2019 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(102, 102, 102);\\">, applies for members registered with currency THB.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">To qualify, members have to transfer a minimum with THB 200 and more to sportsbook wallet. Each member can claim the bonus once only.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Deposit and bonus amount need to be rollover 20 times before withdrawal can be made.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">The product wallet has a different BONUS Code. Please make sure that you select the correct bonus code for your preferred wallet. </span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>For Example:Transfer deposit amount to Sportsbook wallet: THB 200 / 100% Welcome Bonus: 100% x 200 = 200 / Turnover requirement: (200 +200) x 20 = 8,000</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">Signup bonus taken specifically for Sports cannot be used to play on other products until the rollover requirement is met. Doing so will risk bonus and winning being forfeited.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">If the deposit and bonus are not rolled over for at least 1 time within 30 days after bonus is claimed, the full bonus amount will be forfeited. In the event that a withdrawal is made prior to the fulfilment of the rollover requirement, the bonus and winnings will also be forfeited.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, bets under odd HK 0.5 (equal to under Malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">No Rebates are entitled once you have claimed any of the Welcome Bonus.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time, either for all players or individual player.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem General Promotions Terms &amp; Conditions and Terms of Use apply.</span></li></ol>", "currency": "USD", "description": "Register now and get the bigest bonus only for Empiregem new sign up members."}]',
                    'promotion_type_code'     => 'new_members',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-100%Sign Up Bonus',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567753829_sO7U2uDhn3.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567753843_sUpzHSLeVm.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567753852_rSVCLRQ2ch.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567753858_4qfo4evOZP.jpg',
                    'status'                  => 1,
                    'sort'                    => 1,
                    'admin_name'              => 'christian',
                    'created_at'              => '2019-09-06 15:04:28',
                    'updated_at'              => '2019-09-07 15:10:54',
                ),
            17 =>
                array(
                    'id'                      => 20,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "รับง่ายๆ ได้เต็มๆ100% กับโบนัสสมัครใหม่", "content": "<p><br></p><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(251, 213, 20);\\">﻿ข้อตกลงและเงื่อนไข:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(24, 24, 24);\\">1 ก.ย. 62 เวลา 00:00:00 (GMT +8) ถึงวันที่ 30 ก.ย. 62 เวลา 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(24, 24, 24);\\">, </span><span style=\\"color: rgb(102, 102, 102);\\">สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (THB) เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เพื่อให้ตรงตามเงื่อนไข สมาชิกจะต้องฝากเงินในบัญชีขั้นต่ำ 200 บาท ในหน้ากีฬา และสมาชิกแต่ละท่านจะสามารถรับโบนัสได้เพียงครั้งเดียวเท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เงินฝากและโบนัสที่ได้รับ จะต้องมียอดเดิมพันหมุนเวียน 20 เท่า ถึงจะสามารถทำการถอนออกจากบัญชีได้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">กระเป๋าบัญชี (Wallet) ของแต่ละผลิตภัณฑ์มีรหัสโบนัสที่แต่กต่างกัน โปรดตรวจสอบให้แน่ใจว่าท่านสมาชิกได้เลือกรหัสโบนัสที่ถูกต้องสำหรับกระเป๋าเงินที่คุณต้องการเรียบร้อยแล้ว </span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>ตัวอย่าง: ฝากเงินในหน้ากีฬา: 200 บาท / รับโบนัสต้อนรับ: 200 บาท x 100% = โบนัสจ่ายออก 200 บาท / ยอดเงินหมุนเวียน: (200 บาท +200 บาท) x 20 = 8,000 บาท (ยอดเดิมพันหมุนเวียนทั้งหมด)</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสการสมัคร สามารถใช้ได้เฉพาะหน้ากีฬาเท่านั้น ไม่สามารถใช้เล่นกับผลิตภัณฑ์อื่น ๆ ได้ จนกว่าจะครบยอดเดิมพันหมุนเวียนตามที่กำหนด</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">หากเงินฝากและโบนัสไม่ได้มีการเดิมพันหมุนเวียนอย่างน้อย 1 ครั้ง ภายใน 30 วัน หลังจากได้รับโบนัสแล้วนั้น ยอดโบนัสทั้งหมดจะถูกริบคืน และในกรณีที่มีการถอนเงินก่อนครบยอดเดิมพันหมุนเวียนภายในระยะเวลาที่กำหนด โบนัสและเงินรางวัลจะถูกริบคืน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, การเดิมพันฝั่งตรงข้าม, การเดิมพันต่ำกว่าราคาค่าน้ำฮ่องกง 0.5,&nbsp;(หรือเท่ากับ/ต่ำกว่าราคาค่าน้ำมาเลย์ 0.5, ต่ำกว่าราคาค่าน้ำอินโด -2.00, ต่ำกว่าราคาค่าน้ำ US-200 และต่ำกว่าราคาค่าน้ำเดซิมอล 1.5) เสียครึ่ง, ได้ครึ่ง และไม่รวมรายการม้าแข่ง ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เมื่อสมาชิกทำการรับสิทธิ์โบนัสต้อนรับแล้ว จะไม่สามารถเปลี่ยนแปลงของรางวัลหรือคืนเงินได้ ไม่ว่ากรณีใด ๆ</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการแก้ไข เปลี่ยนแปลงหรือยกเลิกโปรโมชั่น โดยไม่ต้องแจ้งให้ทราบล่วงหน้า</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "สมาชิกใหม่รับเลย โบนัสสุดพิเศษกับ Empiregem"}]',
                    'promotion_type_code'     => 'new_members',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-100%Sign Up Bonus',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567753962_ZYFGnQ2hzK.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567753971_4IezuWZN0F.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567753979_dTStW7UKcu.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567753984_rf8nIbq4fG.jpg',
                    'status'                  => 1,
                    'sort'                    => 1,
                    'admin_name'              => 'christian',
                    'created_at'              => '2019-09-06 15:19:08',
                    'updated_at'              => '2019-09-07 15:34:17',
                ),
            18 =>
                array(
                    'id'                      => 21,
                    'currencies'              => '["USD"]',
                    'languages'               => '[{"title": "150% SIGN UP BONUS ESPORT", "content": "<p><br></p><h2><strong class=\\"ql-size-large\\" style=\\"color: rgb(251, 213, 20);\\">﻿Terms &amp; Conditions:</strong></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">This promotion starts from </span><strong style=\\"color: rgb(24, 24, 24);\\">01/09/2019 00:00:00 (GMT +8) until 30/09/2019 23:59:59 (GMT+8)</strong><span style=\\"color: rgb(102, 102, 102);\\">, applies for members registered with currency THB</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">To qualify, members have to transfer a minimum with THB 200 and more to sportsbook wallet. Each member can claim the bonus once only.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Deposit and bonus amount need to be rollover 25 times before withdrawal can be made.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Please make sure that you select the correct bonus code for your preferred wallet. </span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>For Example: Transfer deposit amount to Esport wallet: THB 200 / 100% Welcome Bonus: 150% x 200 = 300 / Turnover requirement: (200 +300) x 25 = 12,500</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">Signup bonus taken specifically for Esports cannot be used to play on other products until the rollover requirement is met. Doing so will risk bonus and winning being forfeited.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">If the deposit and bonus are not rolled over for at least 1 time within 30 days after bonus is claimed, the full bonus amount will be forfeited. In the event that a withdrawal is made prior to the fulfilment of the rollover requirement, the bonus and winnings will also be forfeited.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">All draw bets, cancelled bets, voided bets, opposite bets, bets under odd HK 0.5 (equal to under Malay odd 0.5; under Indo odd -2.00; under US odd -200 and under Dec odd 1.5) lose half, win half, horse racing are excluded.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">No Rebates are entitled once you have claimed any of the Welcome Bonus.</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem reserves the right to cancel this promotion at any time, either for all players or individual player.</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">Empiregem General Promotions Terms &amp; Conditions and Terms of Use apply</strong><strong style=\\"color: rgb(102, 102, 102);\\">.</strong></li></ol>", "currency": "USD", "description": "Register now and get the biggest bonus only for Empiregem new sign up members"}]',
                    'promotion_type_code'     => 'new_members',
                    'codes'                   => NULL,
                    'backstage_title'         => 'EN-TH-150% Sign Up Bonus Esport',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567754689_ERQcuZT5N3.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567754697_mRSn3fLAYy.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567754721_vUUgQbnxfN.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567754725_VOf5gI2OXB.jpg',
                    'status'                  => 1,
                    'sort'                    => 2,
                    'admin_name'              => 'christian',
                    'created_at'              => '2019-09-06 15:28:49',
                    'updated_at'              => '2019-09-07 15:17:24',
                ),
            19 =>
                array(
                    'id'                      => 22,
                    'currencies'              => '["THB"]',
                    'languages'               => '[{"title": "สมัครปั๊บ รับเลย!", "content": "<p><br></p><h2><span style=\\"color: rgb(255, 192, 0);\\" class=\\"ql-size-large\\">ข้อตกลงและเงื่อนไข:</span></h2><ol><li><span style=\\"color: rgb(102, 102, 102);\\">โปรโมชั่นนี้เริ่มตั้งแต่วันที่ </span><strong style=\\"color: rgb(24, 24, 24);\\">1 ก.ย. 62 เวลา 00:00:00 (GMT +8) ถึงวันที่ 30 ก.ย. 62 เวลา 23:59:59 (GMT+8)</strong><strong style=\\"color: rgb(102, 102, 102);\\">, </strong><span style=\\"color: rgb(102, 102, 102);\\">สำหรับลูกค้าที่สมัครและลงทะเบียนในสกุลเงินไทยบาท (</span><strong style=\\"color: rgb(102, 102, 102);\\">THB) </strong><span style=\\"color: rgb(102, 102, 102);\\">เท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เพื่อให้ตรงตามเงื่อนไข สมาชิกจะต้องฝากเงินในบัญชีขั้นต่ำ 200 บาท ในหน้า</span><strong style=\\"color: rgb(102, 102, 102);\\"> </strong><span style=\\"color: rgb(102, 102, 102);\\">Esports และสมาชิกแต่ละท่านจะสามารถรับโบนัสได้เพียงครั้งเดียวเท่านั้น</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เงินฝากและโบนัสที่ได้รับ จะต้องมียอดเดิมพันหมุนเวียน 25 เท่า ถึงจะสามารถทำการถอนออกได้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">โปรดตรวจสอบให้แน่ใจว่าท่านสมาชิกได้เลือกรหัสโบนัสที่ถูกต้อง สำหรับกระเป๋าเงินที่คุณต้องการเรียบร้อยแล้ว  </span><sup style=\\"color: rgb(102, 102, 102);\\"><strong><em>ตัวอย่าง: ฝากเงินในหน้า Esport: 200 บาท  /  รับโบนัสต้อนรับ: 200 บาท x 150% = โบนัสจ่ายออก 300 บาท  /  ยอดเงินหมุนเวียน: (200 บาท +300 บาท) x 25 = 12,000 บาท (ยอดเดิมพันหมุนเวียนทั้งหมด)</em></strong></sup></li><li><span style=\\"color: rgb(102, 102, 102);\\">โบนัสการสมัคร สามารถใช้ได้เฉพาะหน้า Esports เท่านั้น ไม่สามารถใช้เล่นกับผลิตภัณฑ์อื่น ๆ ได้ จนกว่าจะครบยอดเดิมพันหมุนเวียนตามที่กำหนด </span></li><li><span style=\\"color: rgb(102, 102, 102);\\">หากเงินฝากและโบนัสไม่ได้มีการเดิมพันหมุนเวียนอย่างน้อย 1 ครั้ง ภายใน 30 วัน หลังจากได้รับโบนัสแล้วนั้น ยอดโบนัสทั้งหมดจะถูกริบคืน และในกรณีที่มีการถอนเงินก่อนครบยอดเดิมพันหมุนเวียนภายในระยะเวลาที่กำหนด โบนัสและเงินรางวัลจะถูกริบคืน</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">การเดิมพันทั้งหมด เช่น การเดิมพันที่เสมอ, การเดิมพันที่ถูกยกเลิก, การเดิมพันที่เป็นโมฆะ, การเดิมพันฝั่งตรงข้าม, การเดิมพันต่ำกว่าราคาค่าน้ำ ฮ่องกง 0.5, &nbsp;(หรือเท่ากับ/ต่ำกว่าราคาค่าน้ำมาเลย์ 0.5, ต่ำกว่าราคาค่าน้ำอินโด -2.00, ต่ำกว่าราคาค่าน้ำ US-200 และต่ำกว่าราคาค่าน้ำเดซิมอล 1.5) เสียครึ่ง, ได้ครึ่ง และไม่รวมรายการม้าแข่ง ซึ่งจะไม่ถูกนำมาคำนวณในโปรโมชั่นนี้</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">เมื่อสมาชิกทำการรับสิทธิ์โบนัสต้อนรับแล้ว จะไม่สามารถเปลี่ยนแปลงของรางวัลหรือคืนเงินได้ ไม่ว่ากรณีใด ๆ</span></li><li><span style=\\"color: rgb(102, 102, 102);\\">Empiregem ขอสงวนสิทธิ์ในการแก้ไข เปลี่ยนแปลงหรือยกเลิกโปรโมชั่น โดยไม่ต้องแจ้งให้ทราบล่วงหน้า</span></li><li><strong style=\\"color: rgb(24, 24, 24);\\">ภายใต้เงื่อนไขและข้อกำหนดทั่วไปของ Empiregem</strong></li></ol>", "currency": "THB", "description": "สมาชิกใหม่รับเลย 150% โบนัสสุดพิเศษกับ Empiregem"}]',
                    'promotion_type_code'     => 'new_members',
                    'codes'                   => NULL,
                    'backstage_title'         => 'TH-TH-150% Sign Up Bonus Esport',
                    'display_start_at'        => '2019-09-01 00:00:00',
                    'display_end_at'          => '2020-09-30 00:00:00',
                    'web_img_path'            => 'uploads/images/201909/06/9_1567755293_ZolFUnOzaI.jpg',
                    'web_content_img_path'    => 'uploads/images/201909/06/9_1567755297_YfKmSOMjKy.jpg',
                    'mobile_img_path'         => 'uploads/images/201909/06/9_1567755303_RTssSb7eBR.jpg',
                    'mobile_content_img_path' => 'uploads/images/201909/06/9_1567755308_5Y6V3PJn1u.jpg',
                    'status'                  => 1,
                    'sort'                    => 2,
                    'admin_name'              => 'margot',
                    'created_at'              => '2019-09-06 15:39:29',
                    'updated_at'              => '2019-09-06 15:39:29',
                ),
        ));


    }
}
