<?php

namespace App\Models;

use App\Models\Traits\FlushCache;
use App\Models\Traits\RememberCache;

class Action extends Model
{
    use RememberCache, FlushCache;

    protected $rememberCacheTag = 'action';

    public static $cacheExpireInMinutes = 43200;

    protected $fillable = [
        'menu_id', 'name', 'method', 'action', 'sort', 'remark', 'url', 'drop_list_url'
    ];

    public function menu()
    {
        return $this->belongsTo(Menu::class);
    }

    public function adminRoles()
    {
        return $this->belongsToMany(AdminRole::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::deleting(function ($model) {
            $model->adminRoles()->detach();
        });

        static::saved(function($model) {
            $model->flushCache();
        });

        static::deleted(function($model) {
            $model->flushCache();
        });
    }
}
