<?php

namespace App\Models;

class AdminRole extends Model
{
    protected $fillable = [
        'name', 'description', 'sort', 'status',
    ];

    protected $casts = [
        'status' => 'boolean',
    ];

    protected $guarded = [];

    public function admins()
    {
        return $this->belongsToMany(Admin::class);
    }

    public function actions()
    {
        return $this->belongsToMany(Action::class)->withTimestamps();
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        # 删除管理员-角色，角色-方法
        static::deleting(function($model) {
            $model->admins()->detach();
            $model->actions()->detach();
        });
    }
}
