<?php

namespace App\Models;

use App\Models\Traits\FlushCache;
use App\Models\Traits\RememberCache;

class Menu extends Model
{
    use RememberCache, FlushCache;

    protected $rememberCacheTag = 'menu';

    public static $cacheExpireInMinutes = 43200;

    protected $casts = [
        'is_show' => 'boolean',
    ];

    public $fillable = [
        'name', 'parent_id', 'path', 'sort', 'is_show', 'description',
    ];

    public function children()
    {
        return $this->hasMany(Menu::class, 'parent_id');
    }

    public function actions()
    {
        return $this->hasMany(Action::class);
    }

    public function isDisplay()
    {
        return ($this->has_action == 0 && $this->children()->count() > 1) || $this->has_action == 1;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        # 将下级菜单父级置为null
        static::deleting(function($model) {
            $model->children()->update(['parent_id' => null]);
            $model->actions()->delete();
        });

        static::saved(function($model) {
            $model->flushCache();
        });

        static::deleted(function($model) {
            $model->flushCache();
        });
    }
}
