<?php
namespace App\Models\Traits;

trait FlushCache
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saved(function($model) {
            $model->flushCache();
        });

        static::deleted(function($model) {
            $model->flushCache();
        });
    }
}